# HyprKnot Example Configuration
# Copy this to config.yaml and modify for your environment

server:
  host: "127.0.0.1"
  port: 8080
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120

knot:
  config_path: "/etc/knot/knot.conf"
  socket_path: "/run/knot/knot.sock"
  knotc_path: "/usr/bin/knotc"
  data_dir: "/var/lib/knot"
  
  # Example zones for VM infrastructure
  allowed_zones:
    - "customers.example.com"           # Customer VM hostnames
    - "10.in-addr.arpa"                # PTR records for 10.x.x.x
    - "172.16.in-addr.arpa"            # PTR records for 172.16.x.x
    - "192.168.in-addr.arpa"           # PTR records for 192.168.x.x

auth:
  enabled: true
  api_keys:
    - "vm-provisioning-api-key-12345"  # For VM provisioning system
    - "customer-portal-api-key-67890"  # For customer self-service portal

log:
  level: "info"
  format: "json"
  output: "/var/log/hyprknot/hyprknot.log"

# Production configuration example:
#
# server:
#   host: "0.0.0.0"  # Listen on all interfaces
#   port: 8080
#
# knot:
#   allowed_zones:
#     - "vms.yourcompany.com"
#     - "10.in-addr.arpa"
#
# auth:
#   enabled: true
#   api_keys:
#     - "secure-production-key-here"
#
# log:
#   level: "info"
#   format: "json"
#   output: "/var/log/hyprknot/hyprknot.log"
