# HyprKnot Configuration File
# Lightweight HTTP API wrapper for KnotDNS

# HTTP Server Configuration
server:
  host: "127.0.0.1"          # Server bind address
  port: 8080                 # Server port
  read_timeout: 30           # Read timeout in seconds
  write_timeout: 30          # Write timeout in seconds
  idle_timeout: 120          # Idle timeout in seconds

# KnotDNS Configuration
knot:
  config_path: "/etc/knot/knot.conf"    # Path to KnotDNS configuration file
  socket_path: "/run/knot/knot.sock"    # Path to KnotDNS control socket
  knotc_path: "/usr/sbin/knotc"         # Path to knotc binary (Debian/Ubuntu default)
  data_dir: "/var/lib/knot"             # KnotDNS data directory

  # Allowed zones - restrict API access to specific zones
  # Leave empty to allow access to all zones
  allowed_zones:
    # - "example.com"
    # - "10.in-addr.arpa"
    # - "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa"

# Authentication Configuration
auth:
  enabled: true               # Enable/disable API authentication
  api_keys:                   # List of valid API keys
    # - "your-secret-api-key-here"
    # - "another-api-key"

# Logging Configuration
log:
  level: "info"               # Log level: debug, info, warn, error, fatal
  format: "json"              # Log format: json, text
  output: "stdout"            # Log output: stdout, stderr, or file path

# Example configuration for production use:
#
# server:
#   host: "0.0.0.0"
#   port: 8080
#
# knot:
#   allowed_zones:
#     - "yourdomain.com"
#     - "10.in-addr.arpa"     # For PTR records in 10.x.x.x range
#
# auth:
#   enabled: true
#   api_keys:
#     - "prod-api-key-12345"
#
# log:
#   level: "info"
#   format: "json"
#   output: "/var/log/hyprknot/hyprknot.log"
